name: strace-static
version: "6.4"
summary: diagnostic, debugging and instructional userspace utility
description: |
  strace is a diagnostic, debugging and instructional userspace utility for Linux
build-base: core22
base: bare
confinement: strict

apps:
  strace-static:
    command: bin/strace

parts:
  strace:
    plugin: autotools
    source: https://github.com/strace/strace/releases/download/v6.4/strace-6.4.tar.xz
    build-packages:
      - gawk
      - on s390x:
        - g++-multilib
        - gcc-multilib
      - on amd64:
        - g++-multilib
        - gcc-multilib
        - libiberty-dev
        - libunwind-dev
    override-pull: |
      craftctl default
      patch -p1 < ${CRAFT_PROJECT_DIR}/0001-strace-add-new-uid-gid-options-for-static-linking.patch
    autotools-configure-parameters:
      - --prefix=/
      - --enable-mpers=check
      - LDFLAGS='-static -pthread'
    prime:
      - bin/strace
